#!/bin/bash

POSTGRES_SERVER_FQDN=$1
POSTGRES_ADMIN_USERNAME=$2
POSTGRES_ADMIN_PASSWORD=$3
POSTGRES_DATABASE_NAME=$4
POSTGRES_BACKUP_FILE=$5

PGPASSWORD=$POSTGRES_ADMIN_PASSWORD pg_restore -h $POSTGRES_SERVER_FQDN -U $POSTGRES_ADMIN_USERNAME -d $POSTGRES_DATABASE_NAME -1 $POSTGRES_BACKUP_FILE